---
apiVersion: v1
kind: Secret
metadata:
  name: som3-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/som3-frontend-gitops
